import type {
  ArrivalRoute,
  ChecklistItem,
  GameGuideItem,
  GuideCard,
  ToolkitItem,
  VenueItem,
} from './types';

export const assets = {
  splash: require('../../assets/hero/night-entry-welcome.png'),
  mark: require('../../assets/brand/berlin-guest-compass-mark.png'),
  hubHero: require('../../assets/hero/potsdamer-evening-arrival.png'),
  tableFloor: require('../../assets/hero/table-floor-orientation.png'),
  arrivalStairs: require('../../assets/hero/arrival-stairway-notebook.png'),
};

export const appProfile = {
  name: 'Guest Berlin Spielbanken Hub',
  shortName: 'Spielbanken Hub',
  tagline: 'Four official Spielbank Berlin locations, one practical visit notebook.',
  supportPhone: '+49 30 255 99 0',
  supportEmail: 'info@spielbank-berlin.de',
  officialWebsite: 'https://www.spielbank-berlin.de/',
  locationsWebsite: 'https://www.spielbank-berlin.de/en/locations/',
  rulesWebsite: 'https://www.spielbank-berlin.de/haus-und-spielordnung/',
  admission: '18+ with valid official photo ID. Standard entrance fee is EUR 2.00.',
  dressCode: 'Neat casual is welcome; Berlin style is relaxed, but clothing should be appropriate.',
  regularClosingNote:
    'Regular hours are shown in the app. Closing days and holiday changes should be checked on the official website before visiting.',
};

export const onboardingSlides = [
  {
    image: assets.hubHero,
    title: 'Choose the right Spielbank Berlin venue',
    text: 'Compare Potsdamer Platz, TV Tower, Ku-damm, and Ellipse Spandau by games, hours, arrival, and visitor mood.',
  },
  {
    image: assets.tableFloor,
    title: 'Understand the games before you go',
    text: 'Read quick, plain-language notes for roulette, blackjack, poker, baccarat, slots, Touchbet, and Ultimate Texas Holdem.',
  },
  {
    image: assets.arrivalStairs,
    title: 'Keep a private visit notebook',
    text: 'Save venues, mark checklist items, store personal notes, and open real calls, routes, maps, and official pages.',
  },
];

export const venues: VenueItem[] = [
  {
    id: 'potsdamer-platz-flagship',
    name: 'Casino am Potsdamer Platz',
    area: 'Potsdamer Platz',
    address: 'Marlene-Dietrich-Platz 1, 10785 Berlin',
    phone: '+49 30 255 99 0',
    nearestStop: 'S+U Potsdamer Platz',
    entryFee: 'EUR 2.00',
    regularHours: 'Daily 11:00-03:00',
    tableHours: ['American Roulette 17:00-03:00', 'Black Jack 17:00-03:00', 'Poker floor from 18:00'],
    games: ['American Roulette', 'Black Jack', 'Poker', 'Punto Banco / Baccarat', 'Slots', 'Touchbet', 'Sic Bo'],
    image: require('../../assets/venues/list/potsdamer-plaza-evening-card.png'),
    detailImage: require('../../assets/venues/detail/potsdamer-gaming-floor-detail.png'),
    coordinates: {latitude: 52.50745, longitude: 13.37235},
    summary:
      'The main Spielbank Berlin house, central to Potsdamer Platz and useful for visitors who want the broadest game mix.',
    visitorAngle:
      'Best first stop if you want the flagship address, poker floor, classic tables, bars on several levels, and late-night city access.',
    bestFor: 'First-time visitors, poker players, central Berlin nights',
    officialUrl: 'https://www.spielbank-berlin.de/standorte/potsdamer-platz/',
    directionsQuery: 'Marlene-Dietrich-Platz 1, 10785 Berlin',
  },
  {
    id: 'fernsehturm-alexanderplatz',
    name: 'Casino at the TV Tower',
    area: 'Alexanderplatz',
    address: 'Panoramastrasse 1, 10178 Berlin',
    phone: '+49 30 255 99 230',
    nearestStop: 'S+U Alexanderplatz',
    entryFee: 'EUR 2.00',
    regularHours: 'Daily 11:00-03:00',
    tableHours: ['Roulette, Blackjack and Poker Floor from 18:00'],
    games: ['American Roulette', 'Black Jack', 'Poker', 'Slots', 'Touchbet'],
    image: require('../../assets/venues/list/alexanderplatz-tower-evening-card.png'),
    detailImage: require('../../assets/venues/detail/tv-tower-gaming-floor-detail.png'),
    coordinates: {latitude: 52.52084, longitude: 13.40943},
    summary:
      'A landmark-side casino directly by the TV Tower and Alexanderplatz, useful for sightseeing days that turn into evening plans.',
    visitorAngle:
      'Strong pick when your route already runs through Mitte, Museum Island, Alexanderplatz, or the TV Tower area.',
    bestFor: 'Sightseeing routes, central transit, compact evening plans',
    officialUrl: 'https://www.spielbank-berlin.de/en/standorte/casino-on-fernsehturm/',
    directionsQuery: 'Panoramastrasse 1, 10178 Berlin',
  },
  {
    id: 'kudamm-west-berlin',
    name: "Casino on Ku'damm",
    area: 'City West',
    address: 'Kurfuerstendamm 31, 10719 Berlin',
    phone: '+49 30 255 99 320',
    nearestStop: 'U Uhlandstrasse',
    entryFee: 'EUR 2.00',
    regularHours: 'Daily 11:00-03:00',
    tableHours: ['American Roulette 18:00-03:00', 'Blackjack 18:00-03:00', 'Baccarat 18:00-03:00 when available'],
    games: ['American Roulette', 'Black Jack', 'Punto Banco / Baccarat', 'Slots', 'Touchbet', 'Ultimate Texas Holdem'],
    image: require('../../assets/venues/list/city-west-kudamm-evening-card.png'),
    detailImage: require('../../assets/venues/detail/kudamm-gaming-floor-detail.png'),
    coordinates: {latitude: 52.50235, longitude: 13.32684},
    summary:
      'A City West venue on Kurfuerstendamm with two floors and a polished late-evening feel.',
    visitorAngle:
      'Useful after shopping, dinner, Theater des Westens, Zoo, Savignyplatz, or a West Berlin hotel stay.',
    bestFor: 'City West visitors, table-game evenings, hotel-area plans',
    officialUrl: 'https://www.spielbank-berlin.de/en/standorte/casino-on-kudamm/',
    directionsQuery: 'Kurfuerstendamm 31, 10719 Berlin',
  },
  {
    id: 'ellipse-spandau',
    name: 'Casino Ellipse Spandau',
    area: 'Spandau',
    address: 'Altstaedter Ring 1, 13597 Berlin',
    phone: '+49 30 255 99 340',
    nearestStop: 'U Rathaus Spandau',
    entryFee: 'EUR 2.00',
    regularHours: 'Daily 11:00-03:00',
    tableHours: ['Blackjack 18:00-03:00', 'Poker 18:00-02:30', 'Ultimate Texas Holdem 18:00-03:00'],
    games: ['Black Jack', 'Poker', 'Slots', 'Ultimate Texas Holdem'],
    image: require('../../assets/venues/list/spandau-ellipse-evening-card.png'),
    detailImage: require('../../assets/venues/detail/spandau-gaming-floor-detail.png'),
    coordinates: {latitude: 52.53532, longitude: 13.19958},
    summary:
      'A quieter Spandau option near Rathaus Spandau and the old town, with tables and slots away from the central rush.',
    visitorAngle:
      'Best when you are staying west, visiting Spandau, or prefer a less central casino setting.',
    bestFor: 'West-side stays, calmer visits, Spandau routes',
    officialUrl: 'https://www.spielbank-berlin.de/en/standorte/casino-ellipse-spandau/',
    directionsQuery: 'Altstaedter Ring 1, 13597 Berlin',
  },
];

export const gameGuides: GameGuideItem[] = [
  {
    id: 'american-roulette-guide',
    title: 'American Roulette',
    category: 'Classic Tables',
    image: require('../../assets/games/roulette-table-primer.png'),
    summary: 'A wheel-and-number table game offered at several Spielbank Berlin locations.',
    tempo: 'Medium pace',
    beginnerTip: 'Watch one or two rounds first so the table rhythm and closing call feel familiar.',
    offeredAt: ['Potsdamer Platz', 'TV Tower', "Ku'damm"],
    details: ['Ask staff before joining if you are new', 'Table opening times can differ from slot hours', 'Keep chips and cash handling clear'],
  },
  {
    id: 'blackjack-guide',
    title: 'Black Jack',
    category: 'Classic Tables',
    image: require('../../assets/games/blackjack-table-primer.png'),
    summary: 'A card table focused on getting closer to 21 than the dealer without going over.',
    tempo: 'Fast once seated',
    beginnerTip: 'Know your basic decisions before sitting; staff can explain table etiquette, not strategy.',
    offeredAt: ['Potsdamer Platz', 'TV Tower', "Ku'damm", 'Ellipse Spandau'],
    details: ['Hands move quickly', 'Table minimums are posted locally', 'Avoid advising other players at the table'],
  },
  {
    id: 'poker-floor-guide',
    title: 'Poker',
    category: 'Poker',
    image: require('../../assets/games/poker-floor-primer.png'),
    summary: 'Poker is especially relevant at Potsdamer Platz, with additional poker availability at selected venues.',
    tempo: 'Session based',
    beginnerTip: 'Check the official poker information before traveling for a specific cash game or tournament.',
    offeredAt: ['Potsdamer Platz', 'TV Tower', 'Ellipse Spandau'],
    details: ['Poker floor times differ from general opening hours', 'Cash-game details can change', 'Bring valid ID and allow time for registration'],
  },
  {
    id: 'baccarat-guide',
    title: 'Punto Banco / Baccarat',
    category: 'Classic Tables',
    image: require('../../assets/games/baccarat-table-primer.png'),
    summary: 'A classic casino card game listed in the Spielbank Berlin game offering.',
    tempo: 'Measured table pace',
    beginnerTip: 'If Baccarat is your goal, confirm table availability at the exact venue before going.',
    offeredAt: ['Potsdamer Platz', "Ku'damm when available"],
    details: ['Availability may be venue-specific', 'Rules are posted by the casino', 'Good fit for visitors who prefer slower table flow'],
  },
  {
    id: 'slot-machines-guide',
    title: 'Slot Machines',
    category: 'Machines',
    image: require('../../assets/games/slot-machine-primer.png'),
    summary: 'Machine gaming is available across Spielbank Berlin venues during regular opening hours.',
    tempo: 'Self-paced',
    beginnerTip: 'Set a time and spend limit before you start, then use the app checklist to keep it visible.',
    offeredAt: ['Potsdamer Platz', 'TV Tower', "Ku'damm", 'Ellipse Spandau'],
    details: ['Machine areas can open earlier than table games', 'Do not leave credit unattended', 'Use responsible-play limits'],
  },
  {
    id: 'touchbet-guide',
    title: 'Touchbet',
    category: 'Machines',
    image: require('../../assets/games/touchbet-terminal-primer.png'),
    summary: 'Electronic Touchbet options appear in the official venue game mixes.',
    tempo: 'Self-paced with table-style feel',
    beginnerTip: 'Treat it as its own format; do not assume it behaves exactly like a live table.',
    offeredAt: ['Potsdamer Platz', 'TV Tower', "Ku'damm"],
    details: ['Read on-screen rules before play', 'Check venue-specific availability', 'Keep session limits visible'],
  },
  {
    id: 'ultimate-holdem-guide',
    title: 'Ultimate Texas Holdem',
    category: 'Classic Tables',
    image: require('../../assets/games/ultimate-holdem-table-primer.png'),
    summary: 'A casino table variant inspired by Texas Holdem and listed at selected Berlin venues.',
    tempo: 'Medium to fast',
    beginnerTip: 'Learn the betting rounds before joining; it is not the same as a poker-room cash game.',
    offeredAt: ['Potsdamer Platz', "Ku'damm", 'Ellipse Spandau'],
    details: ['Table availability can change', 'Rules are explained locally', 'Good alternative when you want poker-like decisions without a poker table seat'],
  },
];

export const toolkitItems: ToolkitItem[] = [
  {
    id: 'first-visit-id-check',
    icon: 'ID',
    title: 'First Visit: ID and Entry',
    tag: 'Admission',
    summary: 'Know the 18+ rule, official photo ID requirement, and standard EUR 2.00 entry fee before you arrive.',
    details: ['Bring passport or official identity card', 'Driving licences and informal cards may not be enough', 'Guest registration happens at entry'],
    actionLabel: 'Open First Visit Guide',
    action: 'guide',
  },
  {
    id: 'dress-code-context',
    icon: 'DC',
    title: 'Dress Code Context',
    tag: 'Comfort',
    summary: 'Berlin casino style is relaxed, but guests should arrive neat and appropriately dressed.',
    details: ['No evening gown or tie is required by default', 'Avoid beachwear or careless sportswear', 'Dress up if the evening plan calls for it'],
    actionLabel: 'Open Guide',
    action: 'guide',
  },
  {
    id: 'player-card-note',
    icon: 'PC',
    title: 'Player Card Note',
    tag: 'Entry',
    summary: 'The official Player Card can simplify entry and is handled by Spielbank Berlin, not by this app.',
    details: ['Registration is free according to the official locations page', 'Membership is renewed annually', 'Benefits are casino-specific'],
    actionLabel: 'Open Website',
    action: 'website',
  },
  {
    id: 'arrival-router',
    icon: 'AR',
    title: 'Arrival Router',
    tag: 'Transport',
    summary: 'Compare common public transport and walking routes before choosing a venue.',
    details: ['Potsdamer Platz is best for central routes', 'Alexanderplatz fits TV Tower plans', 'Rathaus Spandau fits the Ellipse venue'],
    actionLabel: 'Open Routes',
    action: 'arrival',
  },
  {
    id: 'official-contact',
    icon: 'TEL',
    title: 'Official Contact',
    tag: 'Contact',
    summary: 'Use the venue phone numbers for current table availability, holiday hours, and official questions.',
    details: ['The app keeps planning local', 'Calls open the phone app', 'Always confirm current details for special dates'],
    actionLabel: 'Call Main Number',
    action: 'call',
  },
  {
    id: 'responsible-play',
    icon: 'RG',
    title: 'Responsible Play Check',
    tag: 'Safety',
    summary: 'Keep time, spend, and exit plans visible before you enter the gaming floor.',
    details: ['Set a personal limit', 'Take breaks away from the table or machines', 'Use official prevention/player-protection resources if needed'],
    actionLabel: 'Open Notes',
    action: 'notes',
  },
  {
    id: 'city-map',
    icon: 'MAP',
    title: 'Four-Venue Map',
    tag: 'Map',
    summary: 'Review all four Spielbank Berlin addresses and pick the one that fits your route.',
    details: ['Potsdamer Platz', 'TV Tower / Alexanderplatz', "Ku'damm / City West", 'Ellipse Spandau'],
    actionLabel: 'Open Map',
    action: 'map',
  },
  {
    id: 'closing-days',
    icon: '360',
    title: 'Closing Days Reminder',
    tag: 'Hours',
    summary: 'Spielbank Berlin states regular operation on 360 days per year, with several annual closing days.',
    details: ['Good Friday', 'Memorial Day / Volkstrauertag', 'Sunday of the Dead / Totensonntag', 'Christmas Eve and Christmas Day'],
    actionLabel: 'Open Website',
    action: 'website',
  },
];

export const arrivalRoutes: ArrivalRoute[] = [
  {
    id: 'route-potsdamer-central',
    title: 'Central Berlin to Potsdamer Platz',
    icon: 'U2',
    from: 'Alexanderplatz or Stadtmitte',
    duration: 'About 10-18 min',
    cost: 'BVG/VBB ticket',
    steps: ['Take U2 toward Potsdamer Platz', 'Exit toward Marlene-Dietrich-Platz', 'Walk across the plaza to the casino entrance'],
    note: 'Best default route for first-time visitors staying in Mitte.',
  },
  {
    id: 'route-tv-tower',
    title: 'Directly to the TV Tower venue',
    icon: 'S+U',
    from: 'Alexanderplatz',
    duration: 'About 3-7 min walk',
    cost: 'Usually no extra fare once nearby',
    steps: ['Arrive at S+U Alexanderplatz', 'Follow signs toward Fernsehturm', 'Continue to Panoramastrasse 1'],
    note: 'Works well after sightseeing around the TV Tower or Museum Island.',
  },
  {
    id: 'route-kudamm-west',
    title: "City West to Ku'damm",
    icon: 'U1',
    from: 'Zoologischer Garten or Wittenbergplatz',
    duration: 'About 6-15 min',
    cost: 'BVG/VBB ticket',
    steps: ['Travel toward Uhlandstrasse or Kurfuerstendamm', 'Exit toward Kurfuerstendamm 31', 'Check table hours before entering'],
    note: 'Strong route after dinner, shopping, or a West Berlin hotel stay.',
  },
  {
    id: 'route-spandau-ellipse',
    title: 'Rathaus Spandau to Ellipse',
    icon: 'U7',
    from: 'Rathaus Spandau',
    duration: 'About 2-6 min walk',
    cost: 'BVG/VBB ticket',
    steps: ['Arrive at U Rathaus Spandau', 'Use the Altstaedter Ring exit', 'Walk toward the Ellipse building'],
    note: 'Best if your day is already in Spandau or west Berlin.',
  },
];

export const guideCards: GuideCard[] = [
  {
    id: 'entry-reality',
    icon: 'ID',
    eyebrow: 'Admission',
    title: 'Entry is handled only at the casino',
    body: 'This app helps you prepare. It does not issue tickets, access rights, or Player Cards.',
    details: ['Minimum age is 18', 'Official photo ID is required', 'Entry fee is paid at the venue', 'House rules apply after entry'],
  },
  {
    id: 'choose-venue',
    icon: '4X',
    eyebrow: 'Venues',
    title: 'Pick by route, not just by name',
    body: 'Potsdamer Platz is the broadest hub, TV Tower is sightseeing-friendly, Ku-damm fits City West, and Spandau is calmer.',
    details: ['Check the nearest station', 'Compare table hours', 'Save one or more venues', 'Open directions before leaving'],
  },
  {
    id: 'table-timing',
    icon: '18H',
    eyebrow: 'Hours',
    title: 'Table games can start later',
    body: 'Regular casino hours and table-specific hours are not always the same, especially for poker and classic tables.',
    details: ['Slots may be available earlier', 'Poker can have separate times', 'Holiday hours can change', 'Call or check official pages for special dates'],
  },
  {
    id: 'responsible-visit',
    icon: 'RG',
    eyebrow: 'Safety',
    title: 'Plan your limit before the floor',
    body: 'Use the notebook to write a time limit, spend limit, exit route, and a quick personal reminder.',
    details: ['Avoid chasing losses', 'Take a break if the plan changes', 'Keep transport ready', 'Use official player-protection resources when needed'],
  },
];

export const checklistItems: ChecklistItem[] = [
  {
    id: 'valid-photo-id',
    title: 'Bring official photo ID',
    description: 'Passport or official identity card is the safest choice for entry registration.',
  },
  {
    id: 'check-current-hours',
    title: 'Check current hours',
    description: 'Use the official page for holiday changes, special dates, and table availability.',
  },
  {
    id: 'choose-venue-route',
    title: 'Choose the venue by route',
    description: 'Match your plan to Potsdamer Platz, Alexanderplatz, City West, or Spandau.',
  },
  {
    id: 'set-personal-limit',
    title: 'Set a personal limit',
    description: 'Write down a spend/time limit before entering the gaming area.',
  },
  {
    id: 'save-exit-plan',
    title: 'Save your exit plan',
    description: 'Keep transit, taxi, or walking route ready for late-night departure.',
  },
];

export const visitorZones = ['Entrance', 'ID check', 'Cash desk', 'Table games', 'Machines', 'Bars', 'Exit route'];
